### ISSUE TITLE
v1: Truffle deploy: Cannot convert 0x-4 to a BigInt.

### ISSUE THREAD

**Issue by Kuzirashi** [nervosnetwork/godwoken-web3#238]
Demo repository: https://github.com/DeadGamesInc/nervos-testing

Result:
```
"OblivionBasicNft" -- Cannot convert 0x-4 to a BigInt.

at C:\Users\barry\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\deployer\src\deployment.js:365:1
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at Migration._deploy (C:\Users\barry\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:75:1)
at Migration._load (C:\Users\barry\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:61:1)
at Migration.run (C:\Users\barry\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:218:1)
at Object.runMigrations (C:\Users\barry\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:150:1)
at Object.runFrom (C:\Users\barry\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:110:1)
at runMigrations (C:\Users\barry\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:253:1)
at Object.run (C:\Users\barry\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:223:1)
at Command.run (C:\Users\barry\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command.js:167:1)
```

**Comment by RetricSu** [comment]
hi, I check the code and found out that somehow in the code you provided truffle will use signing scheme before [eip155](https://eips.ethereum.org/EIPS/eip-155). I think currently we only support eip155 signing(which will include chainId for replay attack protection). 

I am not familiar with truffle, but maybe one possible workaround will be to config truffle to use eip155 signing scheme.

here we do need more docs and more friendly error message about not supporting old signing scheme before eip155.

**Comment by Kuzirashi** [comment]
Alright, that was it.

This answer fixed it: https://ethereum.stackexchange.com/a/110720/24685
