### ISSUE TITLE
[v1]eth_estimateGas return data out-of-bounds

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/godwoken-web3#286]
invoke contains assert method return data out-of-bounds
### step
1. deploy  CallReceiverMock
2. call mockFunctionThrows use hardhat 
#### solidity  
```
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

contract CallReceiverMock {
    string public sharedAnswer;

    event MockFunctionCalled();
    event MockFunctionCalledWithArgs(uint256 a, uint256 b);

    uint256[] private _array;

    function mockFunction() public payable returns (string memory) {
        emit MockFunctionCalled();

        return "0x1234";
    }

    function mockFunctionWithArgs(uint256 a, uint256 b) public payable returns (string memory) {
        emit MockFunctionCalledWithArgs(a, b);

        return "0x1234";
    }

    function mockFunctionNonPayable() public returns (string memory) {
        emit MockFunctionCalled();

        return "0x1234";
    }

    function mockStaticFunction() public pure returns (string memory) {
        return "0x1234";
    }

    function mockFunctionRevertsNoReason() public payable {
        revert();
    }

    function mockFunctionRevertsReason() public payable {
        revert("CallReceiverMock: reverting");
    }

    function mockFunctionThrows() public payable {
        assert(false);
    }

    function mockFunctionOutOfGas() public payable {
        for (uint256 i = 0; ; ++i) {
            _array.push(i);
        }
    }

    function mockFunctionWritesStorage() public returns (string memory) {
        sharedAnswer = "42";
        return "0x1234";
    }
}
```
#### js
```
const {ethers} = require("hardhat");
const {expect} = require("chai");
const {getTxReceipt} = require("../rpc/utils/tx");


describe("Multicall_bug ", function () {


    let contract;
    let  contractInfo;
    before(async function () {
        contractInfo = await ethers.getContractFactory("CallReceiverMock");

    });

    it("reverts when the called function throws",async ()=>{
        console.log("begin")
        contract = await contractInfo.deploy();
        await contract.deployed();
        console.log("invoke assert method")
        let tx = await contract.mockFunctionThrows();
        await tx.wait()

    }).timeout(40000)
})
```
#### response
```
begin
jsonRpcRequest: { jsonrpc: '2.0', method: 'web3_clientVersion', params: [], id: 1 }
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 1,
  result: 'Godwoken/v1.0.0-rc1/linux/node14.19.1'
}
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 3 }
jsonRpcResponse: { jsonrpc: '2.0', id: 3, result: '0x315db00000006' }
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_blockNumber', params: [], id: 4 }
jsonRpcResponse: { jsonrpc: '2.0', id: 4, result: '0x167c5' }
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 5 }
jsonRpcResponse: { jsonrpc: '2.0', id: 5, result: '0x315db00000006' }
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 6 }
jsonRpcResponse: { jsonrpc: '2.0', id: 6, result: '0x315db00000006' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_estimateGas',
  params: [
    {
      from: '0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73',
      data: '0x608060405234801561001057600080fd5b506108a0806100206000396000f3fe6080604052600436106100915760003560e01c8063a793ab4711610059578063a793ab47146100fd578063aa04f77e14610107578063c8fc769614610132578063fc40cf731461015d578063fdb273251461018857610091565b80630c034968146100965780630f63e42c146100a05780632c81d638146100cb5780633bcfaa14146100d55780633e6fec04146100df575b600080fd5b61009e6101b8565b005b3480156100ac57600080fd5b506100b56101f3565b6040516100c29190610648565b60405180910390f35b6100d361025c565b005b6100dd610261565b005b6100e7610272565b6040516100f49190610648565b60405180910390f35b6101056102db565b005b34801561011357600080fd5b5061011c610318565b6040516101299190610648565b60405180910390f35b34801561013e57600080fd5b506101476103a1565b6040516101549190610648565b60405180910390f35b34801561016957600080fd5b506101726103de565b60405161017f9190610648565b60405180910390f35b6101a2600480360381019061019d919061059d565b61046c565b6040516101af9190610648565b60405180910390f35b6040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016101ea9061066a565b60405180910390fd5b60607f52c66ed6ec9ca819cba26fe2b2650059270d8981b295af300187a964f54a8c2360405160405180910390a16040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905090565b600080fd5b60006102705761026f610787565b5b565b60607f52c66ed6ec9ca819cba26fe2b2650059270d8981b295af300187a964f54a8c2360405160405180910390a16040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905090565b60005b6001819080600181540180825580915050600190039060005260206000200160009091909190915055806103119061073e565b90506102de565b60606040518060400160405280600281526020017f3432000000000000000000000000000000000000000000000000000000000000815250600090805190602001906103659291906104e5565b506040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905090565b60606040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905090565b600080546103eb9061070c565b80601f01602080910402602001604051908101604052809291908181526020018280546104179061070c565b80156104645780601f1061043957610100808354040283529160200191610464565b820191906000526020600020905b81548152906001019060200180831161044757829003601f168201915b505050505081565b60607f2b42b3c9af4187c86225f201736204c7597312c830cb5c2537dff6ef24b946ae838360405161049f92919061068a565b60405180910390a16040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905092915050565b8280546104f19061070c565b90600052602060002090601f016020900481019282610513576000855561055a565b82601f1061052c57805160ff191683800117855561055a565b8280016001018555821561055a579182015b8281111561055957825182559160200191906001019061053e565b5b509050610567919061056b565b5090565b5b8082111561058457600081600090555060010161056c565b5090565b60008135905061059781610853565b92915050565b600080604083850312156105b4576105b3610814565b5b60006105c285828601610588565b92505060206105d385828601610588565b9150509250929050565b60006105e8826106b3565b6105f281856106be565b93506106028185602086016106d9565b61060b81610819565b840191505092915050565b6000610623601b836106be565b915061062e8261082a565b602082019050919050565b610642816106cf565b82525050565b6000602082019050818103600083015261066281846105dd565b905092915050565b6000602082019050818103600083015261068381610616565b9050919050565b600060408201905061069f6000830185610639565b6106ac6020830184610639565b9392505050565b600081519050919050565b600082825260208201905092915050565b6000819050919050565b60005b838110156106f75780820151818401526020810190506106dc565b83811115610706576000848401525b50505050565b6000600282049050600182168061072457607f821691505b60208210811415610738576107376107e5565b5b50919050565b6000610749826106cf565b91507fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff82141561077c5761077b6107b6565b5b600182019050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052600160045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602260045260246000fd5b600080fd5b6000601f19601f8301169050919050565b7f43616c6c52656365697665724d6f636b3a20726576657274696e670000000000600082015250565b61085c816106cf565b811461086757600080fd5b5056fea2646970667358221220daf3f8781acd8bf23864255883f3a1e40e148f5007043567c0524f4d81dd521b64736f6c63430008060033'
    }
  ],
  id: 7
}
jsonRpcResponse: { jsonrpc: '2.0', id: 7, result: '0x1da' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_getBlockByNumber',
  params: [ 'latest', false ],
  id: 8
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 8,
  result: {
    number: '0x167c5',
    hash: '0x4cbd6401f13553f09f2a55f019e21ab7f68c87eb57c3da9a4c9a8a57149e782d',
    parentHash: '0x742e78907beb6677c189865d0c288f293ff66df0e9a8016cfefd1d171f445847',
    gasLimit: '0xbebc20',
    gasUsed: '0x0',
    miner: '0x5b434289342adea70423d9cb149a7ecdbf451216',
    size: '0x134',
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    transactions: [],
    timestamp: '0x625ae377',
    mixHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
    nonce: '0x0000000000000000',
    stateRoot: '0x0000000000000000000000000000000000000000000000000000000000000000',
    sha3Uncles: '0x0000000000000000000000000000000000000000000000000000000000000000',
    receiptsRoot: '0x0000000000000000000000000000000000000000000000000000000000000000',
    transactionsRoot: '0x0000000000000000000000000000000000000000000000000000000000000000',
    uncles: [],
    difficulty: '0x8e1bc9bf04000',
    totalDifficulty: '0x8e1bc9bf04000',
    extraData: '0x'
  }
}
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_gasPrice', params: [], id: 9 }
jsonRpcResponse: { jsonrpc: '2.0', id: 9, result: '0x1' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_getTransactionCount',
  params: [ '0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73', 'pending' ],
  id: 10
}
jsonRpcResponse: { jsonrpc: '2.0', id: 10, result: '0xbbe' }
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 11 }
jsonRpcResponse: { jsonrpc: '2.0', id: 11, result: '0x315db00000006' }
eth_sendRawTransaction: {
  gas: <BN: 1da>,
  from: <Buffer 0c 1e fc ca 2b cb 65 a5 32 27 4f 3e f2 4c 04 4e f4 ab 6d 73>,
  data: <Buffer 60 80 60 40 52 34 80 15 61 00 10 57 60 00 80 fd 5b 50 61 08 a0 80 61 00 20 60 00 39 60 00 f3 fe 60 80 60 40 52 60 04 36 10 61 00 91 57 60 00 35 60 e0 ... 2190 more bytes>,
  gasPrice: <BN: 1>,
  to: undefined,
  value: undefined,
  nonce: <BN: bbe>,
  accessList: undefined,
  chainId: undefined,
  maxFeePerGas: undefined,
  maxPriorityFeePerGas: undefined
}
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_sendRawTransaction',
  params: [
    '0xf90916820bbe018201da8080b908c0608060405234801561001057600080fd5b506108a0806100206000396000f3fe6080604052600436106100915760003560e01c8063a793ab4711610059578063a793ab47146100fd578063aa04f77e14610107578063c8fc769614610132578063fc40cf731461015d578063fdb273251461018857610091565b80630c034968146100965780630f63e42c146100a05780632c81d638146100cb5780633bcfaa14146100d55780633e6fec04146100df575b600080fd5b61009e6101b8565b005b3480156100ac57600080fd5b506100b56101f3565b6040516100c29190610648565b60405180910390f35b6100d361025c565b005b6100dd610261565b005b6100e7610272565b6040516100f49190610648565b60405180910390f35b6101056102db565b005b34801561011357600080fd5b5061011c610318565b6040516101299190610648565b60405180910390f35b34801561013e57600080fd5b506101476103a1565b6040516101549190610648565b60405180910390f35b34801561016957600080fd5b506101726103de565b60405161017f9190610648565b60405180910390f35b6101a2600480360381019061019d919061059d565b61046c565b6040516101af9190610648565b60405180910390f35b6040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016101ea9061066a565b60405180910390fd5b60607f52c66ed6ec9ca819cba26fe2b2650059270d8981b295af300187a964f54a8c2360405160405180910390a16040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905090565b600080fd5b60006102705761026f610787565b5b565b60607f52c66ed6ec9ca819cba26fe2b2650059270d8981b295af300187a964f54a8c2360405160405180910390a16040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905090565b60005b6001819080600181540180825580915050600190039060005260206000200160009091909190915055806103119061073e565b90506102de565b60606040518060400160405280600281526020017f3432000000000000000000000000000000000000000000000000000000000000815250600090805190602001906103659291906104e5565b506040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905090565b60606040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905090565b600080546103eb9061070c565b80601f01602080910402602001604051908101604052809291908181526020018280546104179061070c565b80156104645780601f1061043957610100808354040283529160200191610464565b820191906000526020600020905b81548152906001019060200180831161044757829003601f168201915b505050505081565b60607f2b42b3c9af4187c86225f201736204c7597312c830cb5c2537dff6ef24b946ae838360405161049f92919061068a565b60405180910390a16040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905092915050565b8280546104f19061070c565b90600052602060002090601f016020900481019282610513576000855561055a565b82601f1061052c57805160ff191683800117855561055a565b8280016001018555821561055a579182015b8281111561055957825182559160200191906001019061053e565b5b509050610567919061056b565b5090565b5b8082111561058457600081600090555060010161056c565b5090565b60008135905061059781610853565b92915050565b600080604083850312156105b4576105b3610814565b5b60006105c285828601610588565b92505060206105d385828601610588565b9150509250929050565b60006105e8826106b3565b6105f281856106be565b93506106028185602086016106d9565b61060b81610819565b840191505092915050565b6000610623601b836106be565b915061062e8261082a565b602082019050919050565b610642816106cf565b82525050565b6000602082019050818103600083015261066281846105dd565b905092915050565b6000602082019050818103600083015261068381610616565b9050919050565b600060408201905061069f6000830185610639565b6106ac6020830184610639565b9392505050565b600081519050919050565b600082825260208201905092915050565b6000819050919050565b60005b838110156106f75780820151818401526020810190506106dc565b83811115610706576000848401525b50505050565b6000600282049050600182168061072457607f821691505b60208210811415610738576107376107e5565b5b50919050565b6000610749826106cf565b91507fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff82141561077c5761077b6107b6565b5b600182019050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052600160045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602260045260246000fd5b600080fd5b6000601f19601f8301169050919050565b7f43616c6c52656365697665724d6f636b3a20726576657274696e670000000000600082015250565b61085c816106cf565b811461086757600080fd5b5056fea2646970667358221220daf3f8781acd8bf23864255883f3a1e40e148f5007043567c0524f4d81dd521b64736f6c6343000806003387062bb60000002fa0fe4cf7ea1851762841487a4c0d0e274a0ab0f7658120804ca190eec366f79147a00715614b6385e402a83d96ecd70016346ccb14d9c568c498b6c16a109602f5c3'
  ],
  id: 12
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 12,
  result: '0x8fd7e57a469d44094c64d85829d819943c085f4393a7030298b59325f7956de8'
}
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 13 }
jsonRpcResponse: { jsonrpc: '2.0', id: 13, result: '0x315db00000006' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_getTransactionByHash',
  params: [
    '0x8fd7e57a469d44094c64d85829d819943c085f4393a7030298b59325f7956de8'
  ],
  id: 14
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 14,
  result: {
    blockHash: '0x4cbd6401f13553f09f2a55f019e21ab7f68c87eb57c3da9a4c9a8a57149e782e',
    blockNumber: '0x167c6',
    transactionIndex: '0x0',
    from: '0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73',
    gas: '0x1da',
    gasPrice: '0x1',
    hash: '0x8fd7e57a469d44094c64d85829d819943c085f4393a7030298b59325f7956de8',
    input: '0x608060405234801561001057600080fd5b506108a0806100206000396000f3fe6080604052600436106100915760003560e01c8063a793ab4711610059578063a793ab47146100fd578063aa04f77e14610107578063c8fc769614610132578063fc40cf731461015d578063fdb273251461018857610091565b80630c034968146100965780630f63e42c146100a05780632c81d638146100cb5780633bcfaa14146100d55780633e6fec04146100df575b600080fd5b61009e6101b8565b005b3480156100ac57600080fd5b506100b56101f3565b6040516100c29190610648565b60405180910390f35b6100d361025c565b005b6100dd610261565b005b6100e7610272565b6040516100f49190610648565b60405180910390f35b6101056102db565b005b34801561011357600080fd5b5061011c610318565b6040516101299190610648565b60405180910390f35b34801561013e57600080fd5b506101476103a1565b6040516101549190610648565b60405180910390f35b34801561016957600080fd5b506101726103de565b60405161017f9190610648565b60405180910390f35b6101a2600480360381019061019d919061059d565b61046c565b6040516101af9190610648565b60405180910390f35b6040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016101ea9061066a565b60405180910390fd5b60607f52c66ed6ec9ca819cba26fe2b2650059270d8981b295af300187a964f54a8c2360405160405180910390a16040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905090565b600080fd5b60006102705761026f610787565b5b565b60607f52c66ed6ec9ca819cba26fe2b2650059270d8981b295af300187a964f54a8c2360405160405180910390a16040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905090565b60005b6001819080600181540180825580915050600190039060005260206000200160009091909190915055806103119061073e565b90506102de565b60606040518060400160405280600281526020017f3432000000000000000000000000000000000000000000000000000000000000815250600090805190602001906103659291906104e5565b506040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905090565b60606040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905090565b600080546103eb9061070c565b80601f01602080910402602001604051908101604052809291908181526020018280546104179061070c565b80156104645780601f1061043957610100808354040283529160200191610464565b820191906000526020600020905b81548152906001019060200180831161044757829003601f168201915b505050505081565b60607f2b42b3c9af4187c86225f201736204c7597312c830cb5c2537dff6ef24b946ae838360405161049f92919061068a565b60405180910390a16040518060400160405280600681526020017f3078313233340000000000000000000000000000000000000000000000000000815250905092915050565b8280546104f19061070c565b90600052602060002090601f016020900481019282610513576000855561055a565b82601f1061052c57805160ff191683800117855561055a565b8280016001018555821561055a579182015b8281111561055957825182559160200191906001019061053e565b5b509050610567919061056b565b5090565b5b8082111561058457600081600090555060010161056c565b5090565b60008135905061059781610853565b92915050565b600080604083850312156105b4576105b3610814565b5b60006105c285828601610588565b92505060206105d385828601610588565b9150509250929050565b60006105e8826106b3565b6105f281856106be565b93506106028185602086016106d9565b61060b81610819565b840191505092915050565b6000610623601b836106be565b915061062e8261082a565b602082019050919050565b610642816106cf565b82525050565b6000602082019050818103600083015261066281846105dd565b905092915050565b6000602082019050818103600083015261068381610616565b9050919050565b600060408201905061069f6000830185610639565b6106ac6020830184610639565b9392505050565b600081519050919050565b600082825260208201905092915050565b6000819050919050565b60005b838110156106f75780820151818401526020810190506106dc565b83811115610706576000848401525b50505050565b6000600282049050600182168061072457607f821691505b60208210811415610738576107376107e5565b5b50919050565b6000610749826106cf565b91507fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff82141561077c5761077b6107b6565b5b600182019050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052600160045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602260045260246000fd5b600080fd5b6000601f19601f8301169050919050565b7f43616c6c52656365697665724d6f636b3a20726576657274696e670000000000600082015250565b61085c816106cf565b811461086757600080fd5b5056fea2646970667358221220daf3f8781acd8bf23864255883f3a1e40e148f5007043567c0524f4d81dd521b64736f6c63430008060033',
    nonce: '0xbbe',
    to: null,
    value: '0x0',
    v: '0x0',
    r: '0xfe4cf7ea1851762841487a4c0d0e274a0ab0f7658120804ca190eec366f79147',
    s: '0x0715614b6385e402a83d96ecd70016346ccb14d9c568c498b6c16a109602f5c3'
  }
}
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 15 }
jsonRpcResponse: { jsonrpc: '2.0', id: 15, result: '0x315db00000006' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_getTransactionReceipt',
  params: [
    '0x8fd7e57a469d44094c64d85829d819943c085f4393a7030298b59325f7956de8'
  ],
  id: 16
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 16,
  result: {
    transactionHash: '0x8fd7e57a469d44094c64d85829d819943c085f4393a7030298b59325f7956de8',
    transactionIndex: '0x0',
    blockHash: '0x4cbd6401f13553f09f2a55f019e21ab7f68c87eb57c3da9a4c9a8a57149e782e',
    blockNumber: '0x167c6',
    from: '0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73',
    to: null,
    gasUsed: '0x1da',
    cumulativeGasUsed: '0x1da',
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    logs: [],
    contractAddress: '0x5970ada20eae4f57cb194f6b0573b8a7eee5fa82',
    status: '0x1'
  }
}
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_blockNumber', params: [], id: 17 }
jsonRpcResponse: { jsonrpc: '2.0', id: 17, result: '0x167c5' }
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 18 }
jsonRpcResponse: { jsonrpc: '2.0', id: 18, result: '0x315db00000006' }
invoke assert method 
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 19 }
jsonRpcResponse: { jsonrpc: '2.0', id: 19, result: '0x315db00000006' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_estimateGas',
  params: [
    {
      from: '0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73',
      to: '0x5970ada20eae4f57cb194f6b0573b8a7eee5fa82',
      data: '0x3bcfaa14'
    }
  ],
  id: 20
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 20,
  error: {
    code: -32099,
    message: 'data out-of-bounds (length=31, offset=32, code=BUFFER_OVERRUN, version=abi/5.0.7)'
  }
}

ProviderError: data out-of-bounds (length=31, offset=32, code=BUFFER_OVERRUN, version=abi/5.0.7)
    at HttpProvider.request (node_modules/hardhat/internal/core/providers/http.js:50:23)
    at LocalAccountsProvider.request (node_modules/hardhat/internal/core/providers/accounts.js:134:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/internal/ethers-provider-wrapper.js:11:24)

```
#### expected 
```
message not out of bounds
```

**Comment by Flouse** [comment]
```Solidity
function mockFunctionThrows() public payable {
    assert(false);
}
```

The assert function creates an built-in error of type Panic(uint256) -> 0x4e487b71
0x01: If you call assert with an argument that evaluates to false.
evmc_result.output_size => 36
evmc_result.output_data: 0x4e487b710000000000000000000000000000000000000000000000000000000000000001


**Reference:**
https://docs.soliditylang.org/en/v0.8.13/control-structures.html#panic-via-assert-and-error-via-require

**Test Case in Polyjuice**
https://github.com/nervosnetwork/godwoken-polyjuice/blob/4e0a254ef33b98429fc24c20eb6895783b0a27db/polyjuice-tests/src/test_cases/error.rs#L106-L113

@classicalliu

**Comment by gpBlockchain** [comment]
> ```solidity
> function mockFunctionThrows() public payable {
>     assert(false);
> }
> ```
> 
> The assert function creates an built-in error of type Panic(uint256) -> 0x4e487b71 0x01: If you call assert with an argument that evaluates to false. evmc_result.output_size => 36 evmc_result.output_data: 0x4e487b710000000000000000000000000000000000000000000000000000000000000001
> 
> **Reference:** https://docs.soliditylang.org/en/v0.8.13/control-structures.html#panic-via-assert-and-error-via-require
> 
> **Test Case in Polyjuice** https://github.com/nervosnetwork/godwoken-polyjuice/blob/4e0a254ef33b98429fc24c20eb6895783b0a27db/polyjuice-tests/src/test_cases/error.rs#L106-L113
> 
> @classicalliu

I will check if the test case covers all panic scenarios

**Comment by classicalliu** [comment]
Update by
- https://github.com/nervosnetwork/godwoken-web3/pull/308

Error message now:
```
ProviderError: UNPREDICTABLE_GAS_LIMIT: revert: reverted with panic code 0x1 (Assertion error)
```
