### ISSUE TITLE
[CT:v1]no return required error message 

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/godwoken-web3#291]
env:https://godwoken-testnet-web3-v1-rpc.ckbapp.dev
Invokes an error method because `require`, but does not return the error information for `require`
 
### code
```
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;


abstract contract ReentrancyGuard {
    // Booleans are more expensive than uint256 or any type that takes up a full
    // word because each write operation emits an extra SLOAD to first read the
    // slot's contents, replace the bits taken up by the boolean, and then write
    // back. This is the compiler's defense against contract upgrades and
    // pointer aliasing, and it cannot be disabled.

    // The values being non-zero value makes deployment a bit more expensive,
    // but in exchange the refund on every call to nonReentrant will be lower in
    // amount. Since refunds are capped to a percentage of the total
    // transaction's gas, it is best to keep them low in cases like this one, to
    // increase the likelihood of the full refund coming into effect.
    uint256 private constant _NOT_ENTERED = 1;
    uint256 private constant _ENTERED = 2;

    uint256 private _status;

    constructor() {
        _status = _NOT_ENTERED;
    }

    /**
     * @dev Prevents a contract from calling itself, directly or indirectly.
     * Calling a `nonReentrant` function from another `nonReentrant`
     * function is not supported. It is possible to prevent this from happening
     * by making the `nonReentrant` function external, and making it call a
     * `private` function that does the actual work.
     */
    modifier nonReentrant() {
        // On the first call to nonReentrant, _notEntered will be true
        require(_status != _ENTERED, "ReentrancyGuard: reentrant call");

        // Any calls to nonReentrant after this point will fail
        _status = _ENTERED;

        _;

        // By storing the original value once again, a refund is triggered (see
        // https://eips.ethereum.org/EIPS/eip-2200)
        _status = _NOT_ENTERED;
    }
}

abstract contract Context {
    function _msgSender() internal view virtual returns (address) {
        return msg.sender;
    }

    function _msgData() internal view virtual returns (bytes calldata) {
        return msg.data;
    }
}


contract ReentrancyAttack is Context {
    function callSender(bytes4 data) public {
        (bool success, ) = _msgSender().call(abi.encodeWithSelector(data));
        require(success, "ReentrancyAttack: failed call");
    }
}

contract ReentrancyMock is ReentrancyGuard {
    uint256 public counter;

    constructor() {
        counter = 0;
    }

    function callback() external nonReentrant {
        _count();
    }

    function countLocalRecursive(uint256 n) public nonReentrant {
        if (n > 0) {
            _count();
            countLocalRecursive(n - 1);
        }
    }

    function countThisRecursive(uint256 n) public nonReentrant {
        if (n > 0) {
            _count();
            (bool success, ) = address(this).call(abi.encodeWithSignature("countThisRecursive(uint256)", n - 1));
            require(success, "ReentrancyMock: failed call");
        }
    }

    function countAndCall(ReentrancyAttack attacker) public nonReentrant {
        _count();
        bytes4 func = bytes4(keccak256("callback()"));
        attacker.callSender(func);
    }

    function _count() private {
        counter += 1;
    }
}
```
### step 
1. deploy ReentrancyMock
2. deploy ReentrancyAttack
3. invoke ReentrancyMock.countAndCall(ReentrancyAttack.address)
```
  let ReentrancyMockInfo = await ethers.getContractFactory("ReentrancyMock");
        let ReentrancyMockContract = await ReentrancyMockInfo.deploy()
        await ReentrancyMockContract.deployed()
        console.log("contract Address:", ReentrancyMockContract.address)
        let ReentrancyAttackInfo = await ethers.getContractFactory("ReentrancyAttack");
        let ReentrancyAttackContract = await ReentrancyAttackInfo.deploy();
        await ReentrancyAttackContract.deployed();
        console.log("ReentrancyAttackContract Address:", ReentrancyAttackContract.address)
        let tx = await ReentrancyMockContract.countAndCall(ReentrancyAttackContract.address);
        await tx.wait()
```
#### hardhat 
```
ReentrancyAttackContract Address: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
eth_sendTransaction
  Contract call:       ReentrancyMock#countAndCall
  Transaction:         0x9a2e05c62bbcf3178fe0a01615dc8bdcb35a6f073feccb09f99be87fa5a9e817
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3
  Value:               0 ETH
  Gas used:            54485 of 29022680
  Block #3:            0x974db8ce36eb4e6216cf93de0493d0f7318fb3feaacc97f28e5f7397707531e6

  Error: VM Exception while processing transaction: reverted with reason string 'ReentrancyAttack: failed call'
      at ReentrancyAttack.callSender (contracts/bug/ReentrancyMock.sol:63)
      at ReentrancyMock.countAndCall (contracts/bug/ReentrancyMock.sol:96)
      at HardhatNode._mineBlockWithPendingTxs (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1772:23)
      at HardhatNode.mineBlock (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
      at EthModule._sendTransactionAndReturnHash (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1496:18)
      at HardhatNetworkProvider._sendWithLogging (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at HardhatNetworkProvider.request (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at EthersProviderWrapper.send (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)


```
#### bsc
```
ReentrancyAttackContract Address: 0xb1F3b30f8d4cDC2edFe6A51a9d72Ba502Ab955e4
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 40 }
jsonRpcResponse: { jsonrpc: '2.0', id: 40, result: '0x61' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_estimateGas',
  params: [
    {
      from: '0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73',
      to: '0xa25d0965459a81ec1e83c6e80618e8a733e563e1',
      data: '0xb672ad8b000000000000000000000000b1f3b30f8d4cdc2edfe6a51a9d72ba502ab955e4'
    }
  ],
  id: 41
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 41,
  error: {
    code: 3,
    message: 'execution reverted: ReentrancyAttack: failed call',
    data: '0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d5265656e7472616e637941747461636b3a206661696c65642063616c6c000000'
  }
}

Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"name":"ProviderError","code":3,"_isProviderError":true,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d5265656e7472616e637941747461636b3a206661696c65642063616c6c000000"}, method="estimateGas", transaction={"from":"0x0C1EfCCa2Bcb65A532274f3eF24c044EF4ab6D73","to":"0xA25D0965459a81ec1E83C6E80618e8A733e563e1","data":"0xb672ad8b000000000000000000000000b1f3b30f8d4cdc2edfe6a51a9d72ba502ab955e4","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.6.2)
    at Logger.makeError (node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (node_modules/@ethersproject/logger/lib/index.js:242:20)
    at checkError (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:154:16)
    at EthersProviderWrapper.<anonymous> (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:687:47)
    at step (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
#### godwoken 
```
ReentrancyAttackContract Address: 0xC49aD34E68C279741D1b99AC850f84B8e5eF58ba
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 28 }
jsonRpcResponse: { jsonrpc: '2.0', id: 28, result: '0x315db00000006' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_estimateGas',
  params: [
    {
      from: '0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73',
      to: '0x36b89285deb04a98df02b00c71842d343874a367',
      data: '0xb672ad8b000000000000000000000000c49ad34e68c279741d1b99ac850f84b8e5ef58ba'
    }
  ],
  id: 29
}
jsonRpcResponse: { jsonrpc: '2.0', id: 29, result: '0xb9c1' }
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_gasPrice', params: [], id: 30 }
jsonRpcResponse: { jsonrpc: '2.0', id: 30, result: '0x1' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_getTransactionCount',
  params: [ '0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73', 'pending' ],
  id: 31
}
jsonRpcResponse: { jsonrpc: '2.0', id: 31, result: '0xbf3' }
eth_sendRawTransaction: {
  gas: <BN: b9c1>,
  from: <Buffer 0c 1e fc ca 2b cb 65 a5 32 27 4f 3e f2 4c 04 4e f4 ab 6d 73>,
  to: <Buffer 36 b8 92 85 de b0 4a 98 df 02 b0 0c 71 84 2d 34 38 74 a3 67>,
  data: <Buffer b6 72 ad 8b 00 00 00 00 00 00 00 00 00 00 00 00 c4 9a d3 4e 68 c2 79 74 1d 1b 99 ac 85 0f 84 b8 e5 ef 58 ba>,
  gasPrice: <BN: 1>,
  value: undefined,
  nonce: <BN: bf3>,
  accessList: undefined,
  chainId: undefined,
  maxFeePerGas: undefined,
  maxPriorityFeePerGas: undefined
}
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_sendRawTransaction',
  params: [
    '0xf88c820bf30182b9c19436b89285deb04a98df02b00c71842d343874a36780a4b672ad8b000000000000000000000000c49ad34e68c279741d1b99ac850f84b8e5ef58ba87062bb600000030a0cf315823ad29a9d4f23a456823bb728e881e6bced2aee4ee25f815aa61deead0a064e95f8b60253f380bfeb1db202da535dec78948cc98c7ff593e1e39ec0cf712'
  ],
  id: 32
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 32,
  result: '0x73121e7da33baec8d0ec4a2a06fe025486c9669c669dfe5588a18790262326ff'
}
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 33 }
jsonRpcResponse: { jsonrpc: '2.0', id: 33, result: '0x315db00000006' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_getTransactionByHash',
  params: [
    '0x73121e7da33baec8d0ec4a2a06fe025486c9669c669dfe5588a18790262326ff'
  ],
  id: 34
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 34,
  result: {
    hash: '0x73121e7da33baec8d0ec4a2a06fe025486c9669c669dfe5588a18790262326ff',
    blockHash: '0x9ebaaf451e1cb2b3c36365a6f1a842ae3affa79ed0fc2706565ce93772263c19',
    blockNumber: '0x183ff',
    transactionIndex: '0x0',
    from: '0x0000000000000000000000000000000000000000',
    to: null,
    gas: '0xb9b2',
    gasPrice: '0x1',
    input: '0x',
    nonce: '0x0',
    value: '0x0',
    v: '0x0',
    r: '0x0000000000000000000000000000000000000000000000000000000000000000',
    s: '0x0000000000000000000000000000000000000000000000000000000000000000'
  }
}
jsonRpcRequest: { jsonrpc: '2.0', method: 'eth_chainId', params: [], id: 35 }
jsonRpcResponse: { jsonrpc: '2.0', id: 35, result: '0x315db00000006' }
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_getTransactionReceipt',
  params: [
    '0x73121e7da33baec8d0ec4a2a06fe025486c9669c669dfe5588a18790262326ff'
  ],
  id: 36
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 36,
  result: {
    transactionHash: '0x73121e7da33baec8d0ec4a2a06fe025486c9669c669dfe5588a18790262326ff',
    blockHash: '0x9ebaaf451e1cb2b3c36365a6f1a842ae3affa79ed0fc2706565ce93772263c19',
    blockNumber: '0x183ff',
    transactionIndex: '0x0',
    gasUsed: '0xb9b2',
    cumulativeGasUsed: '0xb9b2',
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    logs: [],
    contractAddress: null,
    status: '0x0',
    from: '0x0000000000000000000000000000000000000000',
    to: null,
    failed_reason: { status_code: '0x2', status_type: 'REVERT', message: '' }
  }
}

Error: transaction failed [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transactionHash="0x73121e7da33baec8d0ec4a2a06fe025486c9669c669dfe5588a18790262326ff", transaction={"hash":"0x73121e7da33baec8d0ec4a2a06fe025486c9669c669dfe5588a18790262326ff","type":0,"accessList":null,"blockHash":"0x9ebaaf451e1cb2b3c36365a6f1a842ae3affa79ed0fc2706565ce93772263c19","blockNumber":99327,"transactionIndex":0,"confirmations":1,"from":"0x0000000000000000000000000000000000000000","gasPrice":{"type":"BigNumber","hex":"0x01"},"gasLimit":{"type":"BigNumber","hex":"0xb9b2"},"to":null,"value":{"type":"BigNumber","hex":"0x00"},"nonce":0,"data":"0x","r":"0x0000000000000000000000000000000000000000000000000000000000000000","s":"0x0000000000000000000000000000000000000000000000000000000000000000","v":0,"creates":"0xBd770416a3345F91E4B34576cb804a576fa48EB1","chainId":0}, receipt={"to":null,"from":"0x0000000000000000000000000000000000000000","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0xb9b2"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x9ebaaf451e1cb2b3c36365a6f1a842ae3affa79ed0fc2706565ce93772263c19","transactionHash":"0x73121e7da33baec8d0ec4a2a06fe025486c9669c669dfe5588a18790262326ff","logs":[],"blockNumber":99327,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0xb9b2"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.6.2)
    at Logger.makeError (node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (node_modules/@ethersproject/logger/lib/index.js:242:20)
    at EthersProviderWrapper.<anonymous> (node_modules/@ethersproject/providers/lib/base-provider.js:1676:36)
    at step (node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
### expected 
1. eth_estimateGas return failed 
2. eth_getTransactionReceipt return message contains  "reverted with reason string 'ReentrancyAttack: failed call'"

**Comment by classicalliu** [comment]
Tested with
godwoken: ghcr.io/nervosnetwork/godwoken-prebuilds:v1.1-202204160843
web3: https://github.com/nervosnetwork/godwoken-web3/tree/f7229720a077157fa20a8e5fa951606602581eb2

### eth_estimateGas

```json
{
    "jsonrpc": "2.0",
    "id": 2,
    "error": {
        "code": -32099,
        "message": "UNPREDICTABLE_GAS_LIMIT: revert: ReentrancyAttack: failed call"
    }
}
```

### eth_getTransactionReceipt

```json
{
    "jsonrpc": "2.0",
    "id": 2,
    "result": {
        "transactionHash": "0x63517886f18816e882e352ec1e39fe47039d852e91ceaada971c5e2b75e46381",
        "blockHash": "0xd2796127d89da10016a8271c0786dc1ef53070bfdb31a597174d19f024a01328",
        "blockNumber": "0x1e22",
        "transactionIndex": "0x0",
        "gasUsed": "0xb9c1",
        "cumulativeGasUsed": "0xb9c1",
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "logs": [],
        "contractAddress": null,
        "status": "0x0",
        "from": "0x0000000000000000000000000000000000000000",
        "to": null,
        "failed_reason": {
            "status_code": "0x2",
            "status_type": "REVERT",
            "message": "ReentrancyAttack: failed call"
        }
    }
}
```

meet expectations
