### ISSUE TITLE
[CT:v1] Revert did not return an error message 

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/godwoken-web3#293]
env: https://godwoken-testnet-web3-v1-rpc.ckbapp.dev
invoke `error Empty()`
```
 return error RpcError: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced. RpcError: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, "

```
invoke over-flow method 
```
    message: 'data out-of-bounds (length=15, offset=32, code=BUFFER_OVERRUN, version=abi/5.0.7)'

```
### code 
```
pragma solidity ^0.8.0;

contract RevertError{
    error Empty();

    function testEmpty() public view returns(bool){
        revert Empty();
        return true;
    }

    function addError(uint256 b) public view returns(uint256){
        return type(uint256).max + b;
    }

}
```
#### step 
1. deploy RevertError
2. invoke testEmpty
3. invoke addError(1)
```

describe("RevertError.js ", function () {
//DoubleEndedQueue.test.js
    it("error RpcError: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced. RpcError: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, " +
        "requesting data from a block number that does not exist, or querying a node which is not fully synced.\n",async ()=>{

        let contractInfo = await ethers.getContractFactory("RevertError");
        let contract = await contractInfo.deploy()
        await contract.deployed()
        console.log("contract Address:",contract.address)
        let result = await contract.testEmpty()
    }).timeout(50000)

    it("overflow",async ()=>{
        //expected : execution reverted
        let contractInfo = await ethers.getContractFactory("RevertError");
        let contract = await contractInfo.deploy()
        await contract.deployed()
        console.log("contract Address:",contract.address)
        let result = await contract.addError(0);
        console.log("result:",result)
        result = await contract.addError(1);
    }).timeout(50000)
})

```
#### hardhat-testEmpty
```
eth_call
  Contract call:       RevertError#testEmpty
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3

  Error: VM Exception while processing transaction: reverted with custom error 'Empty()'
      at RevertError.testEmpty (contracts/bug/ErrorBug.sol:7)
      at HardhatNode.runCall (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:615:20)
      at EthModule._callAction (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)
      at HardhatNetworkProvider._sendWithLogging (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at HardhatNetworkProvider.request (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at EthersProviderWrapper.send (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

```
#### godwoken-testEmpty
```
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      from: '0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73',
      to: '0xac2b3b2d2b4299f2ab1b2b053071648e958f16b9',
      data: '0x2db6ad32'
    },
    'latest'
  ],
  id: 18
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 18,
  error: {
    code: -32099,
    message: "Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced."
  }
}

Error: missing revert data in call exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (error={"name":"ProviderError","code":-32099,"_isProviderError":true}, data="0x", code=CALL_EXCEPTION, version=providers/5.6.2)
    at Logger.makeError (node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (node_modules/@ethersproject/logger/lib/index.js:242:20)
    at checkError (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:103:16)
    at EthersProviderWrapper.<anonymous> (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:687:47)
    at step (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
#### bsc-testEmpty
```
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      from: '0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73',
      to: '0x5c074aa13f0528e3b2a071fd4d9b26bd8423e527',
      data: '0x2db6ad32'
    },
    'latest'
  ],
  id: 34
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 34,
  error: { code: 3, data: '0x3db2a12a', message: 'execution reverted' }
}

Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="testEmpty()", errorArgs=[], errorName="Empty", errorSignature="Empty()", reason=null, code=CALL_EXCEPTION, version=abi/5.6.0)
    at Logger.makeError (node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (node_modules/@ethersproject/logger/lib/index.js:242:20)
    at Interface.decodeFunctionResult (node_modules/@ethersproject/abi/lib/interface.js:382:23)
    at Contract.<anonymous> (node_modules/@ethersproject/contracts/lib/index.js:395:56)
    at step (node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
#### hardhat-addError
```
eth_call
  Contract call:       RevertError#addError
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512

  Error: VM Exception while processing transaction: reverted with panic code 0x11 (Arithmetic operation underflowed or overflowed outside of an unchecked block)
      at RevertError.addError (contracts/bug/ErrorBug.sol:12)
      at HardhatNode.runCall (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:615:20)
      at EthModule._callAction (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)
      at HardhatNetworkProvider._sendWithLogging (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at HardhatNetworkProvider.request (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at EthersProviderWrapper.send (/Users/guopenglin/projects/gp/godwoken-acceptance/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)


```
#### bsc-addError
```
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      from: '0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73',
      to: '0x12b1cd880fd60930d20072faf52e68a0ed56ad62',
      data: '0x7b45806f0000000000000000000000000000000000000000000000000000000000000001'
    },
    'latest'
  ],
  id: 57
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 57,
  error: {
    code: 3,
    data: '0x4e487b710000000000000000000000000000000000000000000000000000000000000011',
    message: 'execution reverted'
  }
}

Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="addError(uint256)", errorArgs=[{"type":"BigNumber","hex":"0x11"}], errorName="Panic", errorSignature="Panic(uint256)", reason=null, code=CALL_EXCEPTION, version=abi/5.6.0)
    at Logger.makeError (node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (node_modules/@ethersproject/logger/lib/index.js:242:20)
    at Interface.decodeFunctionResult (node_modules/@ethersproject/abi/lib/interface.js:382:23)
    at Contract.<anonymous> (node_modules/@ethersproject/contracts/lib/index.js:395:56)
    at step (node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
#### godwoken-addError
```
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_call',
  params: [
    {
      from: '0x0c1efcca2bcb65a532274f3ef24c044ef4ab6d73',
      to: '0x495c162057a88305e461bf28811cdc5699f1a32c',
      data: '0x7b45806f0000000000000000000000000000000000000000000000000000000000000001'
    },
    'latest'
  ],
  id: 20
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 20,
  error: {
    code: -32099,
    message: 'data out-of-bounds (length=15, offset=32, code=BUFFER_OVERRUN, version=abi/5.0.7)'
  }
}
```
#### expected 
1. invoke testEmpty return reverted
2. invoke addError didn't return  data out-of-bounds

**Comment by Flouse** [comment]
```Solidity
function addError(uint256 b) public view returns(uint256){
    return type(uint256).max + b;
}
```

If an arithmetic operation results in underflow or overflow outside of an unchecked { ... } block,
an built-in error Panic(0x11) will be throwed.

**Reference:**
https://docs.soliditylang.org/en/v0.8.13/control-structures.html#panic-via-assert-and-error-via-require

**Test case in Polyjuice**
https://github.com/nervosnetwork/godwoken-polyjuice/blob/4e0a254ef33b98429fc24c20eb6895783b0a27db/polyjuice-tests/src/test_cases/error.rs#L144-L148

@classicalliu

**Comment by classicalliu** [comment]
Update by
- https://github.com/nervosnetwork/godwoken-web3/pull/308

For `testEmpty()`
```
  reason: 'missing revert data in call exception',
  code: 'CALL_EXCEPTION',
  error: ProviderError: revert: reverted with custom error
```


For `addError()`
```
  reason: 'missing revert data in call exception',
  code: 'CALL_EXCEPTION',
  error: ProviderError: revert: reverted with panic code 0x11 (Arithmetic operation underflowed or overflowed outside of an unchecked block)
```

**Comment by gpBlockchain** [comment]
pragma solidity ^0.8.0;

contract RevertError{
    error Empty();

    function testEmpty() public view returns(bool){
        revert Empty();
        return true;
    }

    function addError(uint256 b) public view returns(uint256){
        return type(uint256).max + b;
    }

}

eth_call :testEmpty()
godwoken
{
  "code": -32099,
  "message": "revert: reverted with custom error"
}

eth
----------
{
  "originalError": {
    "code": 3,
    "data": "0x3db2a12a",
    "message": "execution reverted"
  }
}
---
