### ISSUE TITLE
connect EADDRNOTAVAIL error

### ISSUE THREAD

**Issue by ShiningRay** [nervosnetwork/godwoken-web3#303]
我们的web3进程会报以下错误

```
web3_1      | 03:52:50 0|gw-web3  | [error]  JSONRPC Server Error: [bound get_script_hash] Error: request to http://godwoken:8119/ failed, reason: connect EADDRNOTAVAIL 172.19.0.8:8119 - Local (172.19.0.7:0) Error: request to http://godwoken:8119/ failed, reason: connect EADDRNOTAVAIL 172.19.0.8:8119 - Local (172.19.0.7:0)
web3_1      | 03:52:50 0|gw-web3  |     at Object.parseGwRpcError (/godwoken-web3/packages/api-server/lib/methods/gw-error.js:138:15)
web3_1      | 03:52:50 0|gw-web3  |     at Gw.get_script_hash (/godwoken-web3/packages/api-server/lib/methods/modules/gw.js:198:24)
web3_1      | 03:52:50 0|gw-web3  |     at runMicrotasks (<anonymous>)
web3_1      | 03:52:50 0|gw-web3  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
web3_1      | 03:52:50 0|gw-web3  |     at async Gw.get_script_hash (/godwoken-web3/packages/api-server/lib/methods/validator.js:28:20)
web3_1      | 03:52:50 0|gw-web3  |     at async Server.methods.<computed> (/godwoken-web3/packages/api-server/lib/methods/index.js:49:36)
```

导致RPC间歇性的报错
我们的godwoken一套都是跑在docker里面的，在同一台服务器上

**Comment by Flouse** [comment]
PRs:
- v1: https://github.com/nervosnetwork/godwoken-web3/pull/304
- v0: TBD @RetricSu
