### ISSUE TITLE
[Incompatibility with Rinkeby] "contractAddress" should be "null" instead of "0x" in transaction receipt

### ISSUE THREAD

**Issue by Kuzirashi** [nervosnetwork/godwoken-web3#363]
# Problem

Expected: contractAddress is null instead of 0x when no contract addresses have been created in transaction
Actual: contractAddress is 0x

# Context

This is blocking Gnosis Safe deployment because Gnosis Safe indexer in Python errors with:
```
ValueError: Could not format invalid value '0x' as field 'contractAddress'
```

Bigger log from safe-transaction-service:
```
 2022-05-27 14:40:33,627 [INFO] [a6e16846/index_erc20_events_task] Start indexing of erc20/721 events
worker_1     | 2022-05-27 14:40:33,865 [INFO] [a6e16846/index_erc20_events_task] Indexing of erc20/721 events task processed 0 events
worker_1     | 2022-05-27 14:40:33,870 [INFO] [a6e16846/index_erc20_events_task] Task safe_transaction_service.history.tasks.index_erc20_events_task[a6e16846-d558-4f83-a8ad-c65a4c447b56] succeeded in 0.24298460000136402s: 0
worker_1     | 2022-05-27 14:40:34,627 [INFO] [8b911d0c/index_safe_events_task] Start indexing of Safe events
worker_1     | 2022-05-27 14:40:34,874 [INFO] [8b911d0c/index_safe_events_task] SafeEventsIndexer: Processing 1 not updated addresses total
worker_1     | 2022-05-27 14:40:34,874 [INFO] [8b911d0c/index_safe_events_task] SafeEventsIndexer: Processing first chunk of 1 not updated addresses
worker_1     | 2022-05-27 14:40:36,026 [INFO] [8b911d0c/index_safe_events_task] SafeEventsIndexer: Found 2 events from block-number=46486 to block-number=54277 for 1 addresses: ['0xC83B6776F16B878d669Ee851FDb3bad97e37eB95']
worker_1     | 2022-05-27 14:40:36,271 [ERROR] [8b911d0c/index_safe_events_task] Task safe_transaction_service.history.tasks.index_safe_events_task[8b911d0c-ae29-4ea2-bbbb-7f21d9ace09b] raised unexpected: ValueError("Could not format invalid value '0x' as field 'contractAddress'")
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python3.10/site-packages/eth_utils/applicators.py", line 84, in apply_formatters_to_dict
worker_1     |     yield key, formatters[key](item)
worker_1     |   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
worker_1     |   File "/usr/local/lib/python3.10/site-packages/eth_utils/applicators.py", line 72, in apply_formatter_if
worker_1     |     return formatter(value)
worker_1     |   File "/usr/local/lib/python3.10/site-packages/eth_utils/address.py", line 110, in to_checksum_address
worker_1     |     norm_address = to_normalized_address(value)
worker_1     |   File "/usr/local/lib/python3.10/site-packages/eth_utils/address.py", line 63, in to_normalized_address
worker_1     |     raise ValueError(
worker_1     | ValueError: Unknown format 0x, attempted to normalize to 0x
worker_1     |
worker_1     | The above exception was the direct cause of the following exception:
worker_1     |
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
worker_1     |     R = retval = fun(*args, **kwargs)
worker_1     |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
worker_1     |     return self.run(*args, **kwargs)
worker_1     |   File "/usr/local/lib/python3.10/site-packages/celery/app/autoretry.py", line 34, in run
worker_1     |     return task._orig_run(*args, **kwargs)
worker_1     |   File "/app/safe_transaction_service/history/tasks.py", line 212, in index_safe_events_task
worker_1     |     number = SafeEventsIndexerProvider().start()
worker_1     |   File "/app/safe_transaction_service/history/indexers/ethereum_indexer.py", line 476, in start
worker_1     |     ) = self.process_addresses(
worker_1     |   File "/app/safe_transaction_service/history/indexers/ethereum_indexer.py", line 383, in process_addresses
worker_1     |     processed_elements = self.process_elements(elements)
worker_1     |   File "/app/safe_transaction_service/history/indexers/events_indexer.py", line 205, in process_elements
worker_1     |     self.index_service.txs_create_or_update_from_tx_hashes(tx_hashes)
worker_1     |   File "/app/safe_transaction_service/history/services/index_service.py", line 172, in txs_create_or_update_from_tx_hashes
worker_1     |     self.ethereum_client.get_transaction_receipts(tx_hashes_not_in_db),
worker_1     |   File "/usr/local/lib/python3.10/site-packages/gnosis/eth/ethereum_client.py", line 1714, in get_transaction_receipts
worker_1     |     receipts.append(receipt_formatter(tx_receipt))
worker_1     |   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
worker_1     |   File "/usr/local/lib/python3.10/site-packages/eth_utils/functional.py", line 45, in inner
worker_1     |     return callback(fn(*args, **kwargs))
worker_1     |   File "/usr/local/lib/python3.10/site-packages/eth_utils/applicators.py", line 90, in apply_formatters_to_dict
worker_1     |     raise ValueError(new_error_message) from exc
worker_1     | ValueError: Could not format invalid value '0x' as field 'contractAddress'
```

# Reproduction

## Rinkeby Gnosis Safe creation transaction receipt:
Request:
```
curl --location --request POST 'https://rinkeby.infura.io/v3/0ebf4dd05d6740f482938b8a80860d13' \
--header 'Content-Type: application/json' \
--data-raw '[
    {
        "jsonrpc": "2.0",
        "method": "eth_getTransactionReceipt",
        "params": [
            "0xd36723aa023d213c9a4b4844b90fa144c6f3a34f4dd0fee53c6b455f419a7ae9"
        ],
        "id": 0
    }
]'
```

Result:
```
[
    {
        "jsonrpc": "2.0",
        "id": 0,
        "result": {
            "blockHash": "0x2a5959f5ac74a7fa69880de44d111c6cb912156ae2e1b00f6f72fac522552920",
            "blockNumber": "0xa406c3",
            "contractAddress": null,
            "cumulativeGasUsed": "0x4b3283",
            "effectiveGasPrice": "0x59682f3a",
            "from": "0xd173313a51f8fc37bcf67569b463abd89d81844f",
            "gasUsed": "0x3f22e",
            "logs": [
                {
                    "address": "0x3b0ef7d22d59590bd9a1d2d8d88c62a0b1a85b98",
                    "blockHash": "0x2a5959f5ac74a7fa69880de44d111c6cb912156ae2e1b00f6f72fac522552920",
                    "blockNumber": "0xa406c3",
                    "data": "0x000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f48f2b2d2a534e402487b3ee7c18c33aec0fe5e40000000000000000000000000000000000000000000000000000000000000001000000000000000000000000d173313a51f8fc37bcf67569b463abd89d81844f",
                    "logIndex": "0x23",
                    "removed": false,
                    "topics": [
                        "0x141df868a6331af528e38c83b7aa03edc19be66e37ae67f9285bf4f8e3c6a1a8",
                        "0x000000000000000000000000a6b71e26c5e0845f74c812102ca7114b6a896ab2"
                    ],
                    "transactionHash": "0xd36723aa023d213c9a4b4844b90fa144c6f3a34f4dd0fee53c6b455f419a7ae9",
                    "transactionIndex": "0x16"
                },
                {
                    "address": "0xa6b71e26c5e0845f74c812102ca7114b6a896ab2",
                    "blockHash": "0x2a5959f5ac74a7fa69880de44d111c6cb912156ae2e1b00f6f72fac522552920",
                    "blockNumber": "0xa406c3",
                    "data": "0x0000000000000000000000003b0ef7d22d59590bd9a1d2d8d88c62a0b1a85b98000000000000000000000000d9db270c1b5e3bd161e8c8503c55ceabee709552",
                    "logIndex": "0x24",
                    "removed": false,
                    "topics": [
                        "0x4f51faf6c4561ff95f067657e43439f0f856d97c04d9ec9070a6199ad418e235"
                    ],
                    "transactionHash": "0xd36723aa023d213c9a4b4844b90fa144c6f3a34f4dd0fee53c6b455f419a7ae9",
                    "transactionIndex": "0x16"
                }
            ],
            "logsBloom": "0x00000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000010000000020000000000000000000000000000000008000000200000000000000000000000000500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000020001000000000000000000000000000000000000000080000000000000000400000000020000000000000100000000000000000",
            "status": "0x1",
            "to": "0xa6b71e26c5e0845f74c812102ca7114b6a896ab2",
            "transactionHash": "0xd36723aa023d213c9a4b4844b90fa144c6f3a34f4dd0fee53c6b455f419a7ae9",
            "transactionIndex": "0x16",
            "type": "0x2"
        }
    }
]
```

## Godwoken Testnet v1.1 Gnosis Safe creation transaction receipt:

Request:
```
curl --location --request POST 'https://godwoken-testnet-v1.ckbapp.dev' \
--header 'Content-Type: application/json' \
--data-raw '[
    {
        "jsonrpc": "2.0",
        "method": "eth_getTransactionReceipt",
        "params": [
            "0xf929c225e250c14781050007d3ff06fde32631acbb4375493db4edd50868ed00"
        ],
        "id": 0
    }
]'
```

Result:
```
[
    {
        "jsonrpc": "2.0",
        "id": 0,
        "result": {
            "transactionHash": "0xf929c225e250c14781050007d3ff06fde32631acbb4375493db4edd50868ed00",
            "blockHash": "0xf8fd5b455d65d309f9ef7a0be87277f70299dd3b429fcf1abcc4ad07638e810b",
            "blockNumber": "0xd3d0",
            "transactionIndex": "0x2",
            "gasUsed": "0xea8e",
            "cumulativeGasUsed": "0x20c02",
            "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
            "logs": [
                {
                    "address": "0x19cc263d722a21f5e373056cf74a6239f72b0bfe",
                    "blockHash": "0xf8fd5b455d65d309f9ef7a0be87277f70299dd3b429fcf1abcc4ad07638e810b",
                    "blockNumber": "0xd3d0",
                    "transactionIndex": "0x2",
                    "transactionHash": "0xf929c225e250c14781050007d3ff06fde32631acbb4375493db4edd50868ed00",
                    "data": "0x0000000000000000000000005dec689ad82315dd8cf25530a6997ea07fb144dc000000000000000000000000c83b6776f16b878d669ee851fdb3bad97e37eb95",
                    "logIndex": "0x0",
                    "topics": [
                        "0x4f51faf6c4561ff95f067657e43439f0f856d97c04d9ec9070a6199ad418e235"
                    ],
                    "removed": false
                }
            ],
            "contractAddress": "0x",
            "status": "0x1",
            "from": "0xd173313a51f8fc37bcf67569b463abd89d81844f",
            "to": "0x19cc263d722a21f5e373056cf74a6239f72b0bfe"
        }
    }
]
```

cc @Flouse @RetricSu

**Comment by Kuzirashi** [comment]
Closing as duplicate of https://github.com/nervosnetwork/godwoken-web3/issues/360.
